# Sprint 2 – Statistics & Mathematics for AI/ML Engineers

## Notebook 14 – Statistics in Machine Learning

**Name:** Mathi Vignesh V  
**Date:** 09/10/2026 

## Objective
To connect statistics to data cleaning, preprocessing, feature engineering, model building, evaluation, dimensionality reduction, clustering, and recommendation systems.

## Learning Approach

For every topic, follow the same three-step learning methodology:

- **Step 1 – Understand the Concept:** Explain the statistical idea, terminology, formula, and purpose.
- **Step 2 – Demonstrate the Concept:** Show a small practical or business example and reason through the result.
- **Step 3 – Implement the Concept:** Implement the concept using Python with readable code and appropriate visualization where useful.
- **Interpretation:** Explain what the result means in practical terms.
- **Key Takeaway:** Summarize the main learning point.

## Evaluation Focus
Conceptual Understanding • Statistical Explanation • Correct Interpretation • Python Implementation • Data Visualization • AI/ML Relevance • Documentation Quality • Code Readability • Problem-Solving • Overall Learning Progress

In [1]:
# Required imports
import numpy as np
import pandas as pd

# Scikit-learn imports used in this notebook
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA


## Data Cleaning

### Step 1 – Understand the Concept
Statistical summaries reveal missingness, impossible ranges, unusual values, and distribution issues.

### Step 2 – Demonstrate the Concept
Profile a dataset before modeling.

In [2]:
df=pd.DataFrame({"age":[22,25,None,31,200],"income":[30,40,45,None,60]})
print(df.describe()); print(df.isna().sum())

              age  income
count    4.000000    4.00
mean    69.500000   43.75
std     87.080423   12.50
min     22.000000   30.00
25%     24.250000   37.50
50%     28.000000   42.50
75%     73.250000   48.75
max    200.000000   60.00
age       1
income    1
dtype: int64


### Interpretation
The profile reveals missing values and a suspicious age value.

### Key Takeaway
Statistical profiling is an early data-quality checkpoint.

## Missing Value Handling

### Step 1 – Understand the Concept
Statistics supports decisions among deletion, imputation, and model-based methods.

### Step 2 – Demonstrate the Concept
Median imputation can be a robust baseline for skewed numeric data.

In [3]:
from sklearn.impute import SimpleImputer
print(SimpleImputer(strategy="median").fit_transform(df[["age","income"]]))

[[ 22.   30. ]
 [ 25.   40. ]
 [ 28.   45. ]
 [ 31.   42.5]
 [200.   60. ]]


### Interpretation
Missing values are replaced using training-data statistics in a proper ML pipeline.

### Key Takeaway
Imputation must avoid data leakage.

## Outlier Detection

### Step 1 – Understand the Concept
IQR, Z-score, robust statistics, and model-based methods identify unusual observations.

### Step 2 – Demonstrate the Concept
Screen a numerical feature using IQR.

In [4]:
q1=df["income"].quantile(.25); q3=df["income"].quantile(.75)
iqr=q3-q1
print(q1-1.5*iqr,q3+1.5*iqr)

20.625 65.625


### Interpretation
Values outside the fences are candidates for investigation.

### Key Takeaway
Outlier flags do not automatically justify removal.

## Feature Engineering

### Step 1 – Understand the Concept
Statistics supports transformations, aggregations, ratios, interactions, and distribution-aware features.

### Step 2 – Demonstrate the Concept
Apply a log transformation to highly skewed monetary data.

In [5]:
income=np.array([100,200,500,1000,5000])
print(np.log1p(income))

[4.61512052 5.30330491 6.2166061  6.90875478 8.51739317]


### Interpretation
Large values are compressed, potentially reducing skewness.

### Key Takeaway
Features should represent useful, prediction-time-available information.

## Feature Scaling

### Step 1 – Understand the Concept
Scaling puts numerical variables on comparable scales; standardization uses mean and standard deviation.

### Step 2 – Demonstrate the Concept
Distance-based models can be dominated by large-unit features.

In [6]:
from sklearn.preprocessing import StandardScaler
X=np.array([[1,100],[2,200],[3,300]])
print(StandardScaler().fit_transform(X))

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


### Interpretation
The transformed columns are centered and scaled based on the fitted data.

### Key Takeaway
Scaling is important for many distance- and gradient-based models.

## Data Normalization

### Step 1 – Understand the Concept
Normalization may refer to bounded rescaling such as min-max scaling; always state the exact transformation.

### Step 2 – Demonstrate the Concept
Map a feature into [0,1].

In [7]:
data = np.array([[10], [20], [30], [40]])
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


### Interpretation
Values are mapped to the selected range using the fitted minimum and maximum.

### Key Takeaway
Do not confuse min-max normalization with standardization.

## Model Evaluation

### Step 1 – Understand the Concept
Statistics supplies metrics, uncertainty concepts, sampling logic, cross-validation, and experiment comparison.

### Step 2 – Demonstrate the Concept
Evaluate regression predictions using MAE and R².

In [8]:
from sklearn.metrics import mean_absolute_error,r2_score
y=[10,20,30,40]; pred=[12,18,29,44]
print(mean_absolute_error(y,pred),r2_score(y,pred))

2.25 0.95


### Interpretation
Different metrics measure different aspects of prediction quality.

### Key Takeaway
Choose metrics based on the ML task and business cost.

## Linear Regression

### Step 1 – Understand the Concept
Models a continuous target as a linear function of predictors.

### Step 2 – Demonstrate the Concept
Estimate sales from advertising spend.

In [9]:
from sklearn.linear_model import LinearRegression
X=np.array([[1],[2],[3],[4],[5]]); y=np.array([3,5,7,8,11])
m=LinearRegression().fit(X,y)
print(m.coef_,m.intercept_,m.score(X,y))

[1.9] 1.0999999999999988 0.9809782608695653


### Interpretation
The slope estimates the model's change in target per unit predictor.

### Key Takeaway
Regression connects statistical relationships with prediction.

## Logistic Regression

### Step 1 – Understand the Concept
Models probability of a binary outcome using a logistic function.

### Step 2 – Demonstrate the Concept
Predict churn/no-churn.

In [10]:
from sklearn.linear_model import LogisticRegression
X=np.array([[1],[2],[3],[4],[5],[6],[7],[8]]); y=[0,0,0,0,1,1,1,1]
m=LogisticRegression().fit(X,y); print(m.predict_proba([[2],[7]])[:,1])

[0.0509552  0.94904376]


### Interpretation
Outputs are estimated class probabilities.

### Key Takeaway
Logistic regression is a probability-based classifier.

## Naive Bayes

### Step 1 – Understand the Concept
Uses Bayes' theorem with a conditional-independence assumption.

### Step 2 – Demonstrate the Concept
Text classification is a common application.

In [11]:
from sklearn.naive_bayes import GaussianNB
X=np.array([[1,0],[1,1],[0,1],[0,0],[1,0],[0,1]]); y=[1,1,0,0,1,0]
m=GaussianNB().fit(X,y); print(m.predict_proba([[1,1]]))

[[0. 1.]]


### Interpretation
The model combines prior and feature evidence under its assumptions.

### Key Takeaway
Bayesian reasoning supports probabilistic classification.

## Clustering

### Step 1 – Understand the Concept
Groups observations by similarity without labeled targets.

### Step 2 – Demonstrate the Concept
Segment customers by behavior.

In [12]:
from sklearn.cluster import KMeans
X=np.array([[1,1],[1,2],[2,1],[8,8],[9,8],[8,9]])
m=KMeans(n_clusters=2,random_state=42,n_init=10).fit(X)
print(m.labels_,m.cluster_centers_)

[0 0 0 1 1 1] [[1.33333333 1.33333333]
 [8.33333333 8.33333333]]


### Interpretation
Clusters and centers summarize the discovered groups.

### Key Takeaway
Scaling, distance, and representation strongly affect clustering.

## Principal Component Analysis (PCA)

### Step 1 – Understand the Concept
Transforms correlated features into orthogonal components ordered by explained variance.

### Step 2 – Demonstrate the Concept
Reduce dimensionality while retaining important variation.

In [13]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
X=np.array([[1,2],[2,4],[3,6],[4,8],[5,10]])
pca=PCA().fit(StandardScaler().fit_transform(X))
print(pca.explained_variance_ratio_)

[1.00000000e+00 1.55638661e-32]


### Interpretation
Explained variance ratio indicates the fraction of standardized-data variance captured by each component.

### Key Takeaway
PCA is statistical dimensionality reduction and is sensitive to scaling.

## Recommendation Systems

### Step 1 – Understand the Concept
Statistics supports user/item summaries, probability estimates, similarity, sampling, experimentation, and evaluation.

### Step 2 – Demonstrate the Concept
Use average item ratings as a simple recommendation baseline.

In [14]:
ratings=pd.DataFrame({"user":[1,1,2,2,3,3],"item":["A","B","A","C","B","C"],"rating":[5,4,4,5,2,4]})
print(ratings.groupby("item")["rating"].agg(["count","mean"]))

      count  mean
item             
A         2   4.5
B         2   3.0
C         2   4.5


### Interpretation
Group statistics provide a simple popularity/quality baseline.

### Key Takeaway
Statistical baselines are useful before complex recommenders.

## End-to-End Statistical ML Workflow

**Data → Profile → Clean → Transform → Engineer Features → Analyze Relationships → Train → Evaluate → Validate → Monitor**

Statistics supports uncertainty, data quality, relationships, transformations, evaluation, experimentation, and communication throughout the ML lifecycle.